---
title: "SISBID"
output: html_document
---

Installing google sheets. For google documents to be accessible: File > Publish to the web
```{r googlesheets}
install.packages("googlesheets")
library(googlesheets)
sheets_url = "https://docs.google.com/spreadsheets/d/18KQQd4LY5k8Ucux1MvWCsQGQJlvd0ECTnn-3ixdOKFM/pubhtml"
gsurl1 = gs_url(sheets_url)
dat = gs_read(gsurl1)
dateAccessed = date()
dateAccessed

```

JSON data

```{r json data}
github_url = "https://api.github.com/users/jtleek/repos"

install.packages("jsonlite")
library(jsonlite)
jsonData <- fromJSON(github_url)
dim(jsonData)
jsonData$name
table(sapply(jsonData,class))
dim(jsonData$owner)
names(jsonData$owner)
head(jsonData$owner)
jsonData$owner$url

github_url = "https://api.github.com/users/hadley/repos"
jsonData <- fromJSON(github_url)
dim(jsonData)
jsonData$stargazers_count # number of stars
jsonData$open_issues_count # number of open issues

```

\texttt{rvest} package

```{r rvest package}
recount_url = "http://bowtie-bio.sourceforge.net/recount/"
install.packages("rvest")
library(rvest)
htmlfile = html(recount_url)


nds = html_nodes(htmlfile,                
xpath='//*[@id="recounttab"]/table')
dat = html_table(nds)
dat = as.data.frame(dat)
head(dat)
```
